# Generated by Django 5.1.15 on 2026-05-22 12:38

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Plan',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.CharField(choices=[('free', 'Free'), ('pro', 'Pro'), ('family', 'Family'), ('institution', 'Institution')], max_length=24, unique=True)),
                ('name', models.CharField(max_length=64)),
                ('price_inr', models.PositiveIntegerField(blank=True, help_text='Price in paise. NULL = sales-led', null=True)),
                ('billing_period', models.CharField(choices=[('none', 'None'), ('monthly', 'Monthly'), ('yearly', 'Yearly')], default='none', max_length=16)),
                ('is_active', models.BooleanField(default=True)),
                ('features', models.JSONField(default=dict, help_text='See apps/billing/constants/plan_features.py')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'ordering': ['price_inr'],
            },
        ),
        migrations.CreateModel(
            name='RazorpayOrder',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('razorpay_order_id', models.CharField(max_length=64, unique=True)),
                ('razorpay_payment_id', models.CharField(blank=True, default='', max_length=64)),
                ('razorpay_payment_link_id', models.CharField(blank=True, default='', max_length=64)),
                ('payment_link_short_url', models.URLField(blank=True, default='')),
                ('amount_inr', models.PositiveIntegerField(help_text='Paise')),
                ('currency', models.CharField(default='INR', max_length=8)),
                ('status', models.CharField(choices=[('created', 'Created'), ('attempted', 'Attempted'), ('paid', 'Paid'), ('failed', 'Failed'), ('expired', 'Expired')], default='created', max_length=16)),
                ('plan_code', models.CharField(max_length=24)),
                ('receipt_id', models.CharField(max_length=64, unique=True)),
                ('raw_webhook_payload', models.JSONField(blank=True, default=dict)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='razorpay_orders', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['user', 'status'], name='billing_raz_user_id_d94f79_idx'), models.Index(fields=['razorpay_payment_id'], name='billing_raz_razorpa_5d850d_idx')],
            },
        ),
        migrations.CreateModel(
            name='Subscription',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.CharField(choices=[('active', 'Active'), ('past_due', 'Past due'), ('cancelled', 'Cancelled'), ('expired', 'Expired')], default='active', max_length=16)),
                ('started_at', models.DateTimeField(blank=True, null=True)),
                ('ends_at', models.DateTimeField(blank=True, help_text='NULL = no expiry (free plan)', null=True)),
                ('razorpay_subscription_id', models.CharField(blank=True, default='', max_length=64)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('plan', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='subscriptions', to='billing.plan')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='subscription', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'indexes': [models.Index(fields=['status'], name='billing_sub_status_948046_idx')],
            },
        ),
        migrations.CreateModel(
            name='UsageQuota',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tool_key', models.CharField(max_length=32)),
                ('day', models.DateField()),
                ('count', models.PositiveIntegerField(default=0)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='usage_quotas', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'indexes': [models.Index(fields=['user', 'day'], name='billing_usa_user_id_2f7c5b_idx')],
                'constraints': [models.UniqueConstraint(fields=('user', 'tool_key', 'day'), name='unique_user_tool_day')],
            },
        ),
    ]
