# Generated by Django 5.1.15 on 2026-05-28 10:56

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='ImageAsset',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('prompt', models.TextField()),
                ('style', models.CharField(blank=True, choices=[('cartoon', 'Cartoon'), ('watercolor', 'Watercolor'), ('crayon', 'Crayon'), ('sketch', 'Sketch'), ('anime', 'Anime'), ('photo_real', 'Photo-Real'), ('isometric', 'Isometric'), ('digital_art', 'Digital Art'), ('pixel', 'Pixel Art')], default='', max_length=32)),
                ('model', models.CharField(blank=True, default='', max_length=64)),
                ('width', models.PositiveSmallIntegerField(default=1024)),
                ('height', models.PositiveSmallIntegerField(default=1024)),
                ('r2_key', models.CharField(blank=True, default='', max_length=255)),
                ('replicate_id', models.CharField(blank=True, default='', max_length=64)),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('succeeded', 'Succeeded'), ('failed', 'Failed')], default='pending', max_length=12)),
                ('error', models.TextField(blank=True, default='')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='image_assets', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['user', '-created_at'], name='image_gen_i_user_id_b55cc7_idx')],
            },
        ),
    ]
