# Generated by Django 5.1.15 on 2026-05-29 09:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('image_gen', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='imageasset',
            name='replicate_id',
        ),
        migrations.AddField(
            model_name='imageasset',
            name='provider_request_id',
            field=models.CharField(blank=True, default='', max_length=64),
        ),
        migrations.AddField(
            model_name='imageasset',
            name='refined_prompt',
            field=models.TextField(blank=True, default=''),
        ),
    ]
