# Generated by Django 5.1.15 on 2026-05-29 10:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('image_gen', '0002_remove_imageasset_replicate_id_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='imageasset',
            name='image_url',
            field=models.URLField(blank=True, default='', max_length=1024),
        ),
    ]
