import factory
from django.contrib.contenttypes.models import ContentType
from factory.django import DjangoModelFactory

from apps.accounts.tests.factories import UserFactory
from apps.image_gen.tests.factories import ImageAssetFactory
from apps.notebook.constants import SourceKind
from apps.notebook.models import NotebookEntry, Tag


class TagFactory(DjangoModelFactory):
    class Meta:
        model = Tag

    user = factory.SubFactory(UserFactory)
    name = factory.Sequence(lambda n: f"tag-{n}")


class NotebookEntryFactory(DjangoModelFactory):
    """Default factory creates an ImageAsset source + matching entry."""

    class Meta:
        model = NotebookEntry
        skip_postgeneration_save = True

    user = factory.SubFactory(UserFactory)
    source_kind = SourceKind.IMAGE_GEN
    title = "An image"
    summary = "An image generated by Vidya"

    @factory.lazy_attribute
    def content_type(self):
        from apps.image_gen.models import ImageAsset

        return ContentType.objects.get_for_model(ImageAsset)

    @factory.lazy_attribute
    def object_id(self):
        asset = ImageAssetFactory(user=self.user)
        return asset.pk
