# Generated by Django 5.1.15 on 2026-05-27 08:12

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='CodeRequest',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('action', models.CharField(choices=[('suggest', 'Suggest'), ('explain', 'Explain'), ('debug', 'Debug'), ('tests', 'Tests')], max_length=16)),
                ('language', models.CharField(choices=[('scratch', 'Scratch'), ('html', 'HTML'), ('css', 'CSS'), ('javascript', 'JavaScript'), ('python', 'Python'), ('sql', 'SQL')], max_length=16)),
                ('code', models.TextField()),
                ('extra', models.TextField(blank=True, default='')),
                ('response', models.TextField(blank=True, default='')),
                ('model', models.CharField(blank=True, default='', max_length=48)),
                ('tokens_in', models.PositiveIntegerField(default=0)),
                ('tokens_out', models.PositiveIntegerField(default=0)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='code_requests', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['user', '-created_at'], name='code_helper_user_id_3e0765_idx')],
            },
        ),
    ]
