# Generated by Django 5.1.15 on 2026-05-29 11:12

import django.contrib.postgres.indexes
import django.contrib.postgres.search
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('contenttypes', '0002_remove_content_type_name'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Tag',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=64)),
                ('slug', models.SlugField(blank=True, max_length=80)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='notebook_tags', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='NotebookEntry',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('source_kind', models.CharField(choices=[('vidya_lm', 'Vidya LM'), ('image_gen', 'Image Gen'), ('code_helper', 'Code Helper')], db_index=True, max_length=16)),
                ('object_id', models.PositiveIntegerField()),
                ('title', models.CharField(blank=True, default='', max_length=240)),
                ('summary', models.TextField(blank=True, default='')),
                ('search_vector', django.contrib.postgres.search.SearchVectorField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('content_type', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='contenttypes.contenttype')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='notebook_entries', to=settings.AUTH_USER_MODEL)),
                ('tags', models.ManyToManyField(blank=True, related_name='entries', to='notebook.tag')),
            ],
            options={
                'ordering': ['-updated_at'],
            },
        ),
        migrations.AddIndex(
            model_name='tag',
            index=models.Index(fields=['user', 'slug'], name='notebook_ta_user_id_6063ed_idx'),
        ),
        migrations.AlterUniqueTogether(
            name='tag',
            unique_together={('user', 'slug')},
        ),
        migrations.AddIndex(
            model_name='notebookentry',
            index=models.Index(fields=['user', '-updated_at'], name='notebook_no_user_id_c14385_idx'),
        ),
        migrations.AddIndex(
            model_name='notebookentry',
            index=models.Index(fields=['user', 'source_kind', '-updated_at'], name='notebook_no_user_id_dcc6fd_idx'),
        ),
        migrations.AddIndex(
            model_name='notebookentry',
            index=django.contrib.postgres.indexes.GinIndex(fields=['search_vector'], name='notebook_no_search__ac126d_gin'),
        ),
        migrations.AddConstraint(
            model_name='notebookentry',
            constraint=models.UniqueConstraint(fields=('user', 'content_type', 'object_id'), name='uq_notebook_per_source'),
        ),
    ]
