# Generated by Django 5.1.15 on 2026-06-01 06:14

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='VideoJob',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('prompt', models.TextField()),
                ('refined_prompt', models.TextField(blank=True, default='')),
                ('model', models.CharField(blank=True, default='fal-ai/kling-video/v1/standard/image-to-video', max_length=128)),
                ('duration_seconds', models.FloatField(blank=True, default=5.0, null=True)),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('running', 'Running'), ('succeeded', 'Succeeded'), ('failed', 'Failed'), ('canceled', 'Canceled')], db_index=True, default='pending', max_length=12)),
                ('error', models.TextField(blank=True, default='')),
                ('seed_image_url', models.URLField(blank=True, default='', max_length=1024)),
                ('seed_image_r2_key', models.CharField(blank=True, default='', max_length=255)),
                ('url', models.URLField(blank=True, default='', max_length=1024)),
                ('r2_key', models.CharField(blank=True, default='', max_length=255)),
                ('provider_request_id', models.CharField(blank=True, default='', max_length=64)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('started_at', models.DateTimeField(blank=True, null=True)),
                ('completed_at', models.DateTimeField(blank=True, null=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='video_jobs', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['user', '-created_at'], name='video_gen_v_user_id_177bdc_idx'), models.Index(fields=['status', 'created_at'], name='video_gen_v_status_837d07_idx')],
            },
        ),
    ]
